Customers = "XPATH://a[@href='#']//p[contains(text(),'Customers')]"
Sub_Customers = "XPATH://a[@href='/Admin/Customer/List']//p[contains(text(),'Customers')]"
Add_Customers = "XPATH://a[@class='btn btn-primary']"
Email = "XPATH://input[@id='Email']"
Password = "XPATH://input[@id='Password']"
First_Name = "XPATH://input[@id='FirstName']"
Last_Name = "XPATH://input[@id='LastName']"
Gender = "NAME:Gender"
Male = "XPATH://input[@id='Gender_Male']"
Female = "XPATH://input[@id='Gender_Female']"
DOB = "XPATH://input[@id='DateOfBirth']"
Company = "XPATH://input[@id='Company']"
IsTaxExempt = "XPATH://input[@id='IsTaxExempt']"

News_Letter = "XPATH://*[@id='customer-info']/div[2]/div[9]/div[2]/div/div[1]/div/div"
Your_Store_Name = "XPATH://span[normalize-space()='Your store name']"
Test_Store_2 = "XPATH://span[normalize-space()='Test store 2']"

Customer_Roles = "XPATH://div[@class='k-multiselect-wrap k-floatwrap']"
Administrators = "XPATH://li[contains(text(),'Administrators')]"
Registered = "XPATH://li[contains(text(),'Registered']"
Guests = "XPATH://li[contains(text(),'Guests')]"
Vendors = "XPATH://li[contains(text(),'Vendors']"

VendorID = "XPATH://select[@id='VendorId']"
Active = "XPATH://input[@id='Active']"
Admin_Comment = "XPATH://textarea[@id='AdminComment']"
Save = "XPATH://button[@name='save']"
