Customers = "xpath://a[@href='#']//p[contains(text(),'Customers')]"
Sub_Customers = "xpath://a[@href='/Admin/Customer/List']//p[contains(text(),'Customers')]"
Add_Customers = "xpath://a[@class='btn btn-primary']"

Email = "xpath://input[@id='Email']"
Password = "xpath://input[@id='Password']"
First_Name = "xpath://input[@id='FirstName']"
Last_Name = "xpath://input[@id='LastName']"
Gender = "Gender"
DOB = "xpath://*[@id='DateOfBirth']"
Company = "xpath://input[@id='Company']"
IsTaxExempt = "xpath://input[@id='IsTaxExempt']"

News_Letter = "xpath://*[@id='customer-info']/div[2]/div[9]/div[2]/div/div[1]/div/div"
Your_Store_Name = "xpath://span[normalize-space()='Your store name']"
Test_Store_2 = "xpath://span[normalize-space()='Test store 2']"

Customer_Roles = "xpath://div[@class='k-multiselect-wrap k-floatwrap']"
Administrators = "xpath://li[contains(text(),'Administrators')]"
Registered = "xpath://li[contains(text(),'Registered']"
Guests = "xpath://li[contains(text(),'Guests')]"
Vendors = "xpath://li[contains(text(),'Vendors']"

VendorID = "XPATH://select[@id='VendorId']"
Active = "XPATH://input[@id='Active']"
Admin_Comment = "XPATH://textarea[@id='AdminComment']"
Save = "XPATH://button[@name='save']"